source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

# inhibit_all_warnings!

def unsafe_ChouTi
	pod 'ChouTi', :path => '../Submodules/ChouTi/'
end

def safe_ChouTi
	pod 'ChouTi/Safe', :path => '../Submodules/ChouTi/'#, :subspecs => ['ChouTi', 'UI']
end

target 'FidoUsage' do

	# Internal Libs
	safe_ChouTi
	pod 'ChouTi/ChouTi', :path => '../Submodules/ChouTi/'
	pod 'ChouTi/UI', :path => '../Submodules/ChouTi/'

	# Utilities
	pod 'Ji', '~> 1.2.0'
	pod 'Alamofire', '~> 3.0'
	pod 'Loggerithm', '~> 1.3'

	pod 'Parse'
	pod 'Watchdog'

	# UI
	pod "DGElasticPullToRefresh", :git => 'https://github.com/honghaoz/DGElasticPullToRefresh.git'
	# Analytics
	# pod 'Google/Analytics'

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'Alamofire' or target.name == 'Ji' or target.name == 'Loggerithm' or target.name == 'ChouTi'
			target.build_configurations.each do |config|
				config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
			end
		end
	end
end
