source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'FidoUsage' do

# Internal Libs
pod 'ChouTi', :path => '../Submodules/ChouTi/'

# Utilities
pod 'Ji'
pod 'Alamofire', '~> 2.0'
pod 'Loggerithm'

pod 'Parse'
pod "Watchdog"

# Analytics
# pod 'Google/Analytics'

end
