source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'FidoUsage' do

# Internal Libs
pod 'ChouTi', :path => '../Submodules/ChouTi/'

# Utilities
pod 'Ji', '~> 1.1.2'
pod 'Alamofire', '~> 2.0'
pod 'Loggerithm', '~> 1.3'
pod "PromiseKit", :git => 'https://github.com/mxcl/PromiseKit', :branch => 'changes-for-3.0'


# Analytics
# pod 'Google/Analytics'

end

target 'FidoUsageTests' do

end

target 'FidoUsageUITests' do

end

